[colors.primary]
background = "@PRIMARY_BACKGROUND@"
foreground = "@PRIMARY_FOREGROUND@"

[colors.normal]
black   = "@NORMAL_BLACK@"
red     = "@NORMAL_RED@"
green   = "@NORMAL_GREEN@"
yellow  = "@NORMAL_YELLOW@"
blue    = "@NORMAL_BLUE@"
magenta = "@NORMAL_MAGENTA@"
cyan    = "@NORMAL_CYAN@"
white   = "@NORMAL_WHITE@"

[colors.bright]
black   = "@BRIGHT_BLACK@"
red     = "@BRIGHT_RED@"
green   = "@BRIGHT_GREEN@"
yellow  = "@BRIGHT_YELLOW@"
blue    = "@BRIGHT_BLUE@"
magenta = "@BRIGHT_MAGENTA@"
cyan    = "@BRIGHT_CYAN@"
white   = "@BRIGHT_WHITE@"
